# Generated by Django 3.0.3 on 2020-03-03 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tourism', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='people_comments',
            name='designation',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
    ]
